name: 'homehub_server'
version: 0.0.1
description: A web server built using the shelf package.
#author: Aitor González Fernández <reimashi@gmail.com>
#homepage: https://github.com/reimashi/homehub

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.10.0 <0.14.0'
  path: '>=1.4.0 <1.5.0'
  shelf: '>=0.6.0 <0.7.0'
  shelf_route: '>=0.14.0 <0.15.0'
  shelf_static: '>=0.2.0 <0.3.0'
  shelf_auth: '>=0.7.0 <0.8.0'
  option: '>=1.2.0 <1.3.0'
  dartson: ">=0.2.0 <0.3.0"
  crypto: ">=2.0.0 <3.0.0"
  collection: ">=1.0.0 <2.0.0"
  sembast : ">=1.3.0 <1.4.0"
